### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MrFunEGUY** [eliasdoehne/stellaris-dashboard#103]
My (heavily modded) game had been going great with the dashboard until the 2380's. Now, whenever I try to parse a save, I get this error:

`MainProcess - 2023-02-11 12:53:45,706 - stellarisdashboard.parsing.timeline - ERROR - imperiumoflosraia_test_2 2387.10.14 Rolling back changes to database...
Traceback (most recent call last):
  File "stellarisdashboard\parsing\timeline.py", line 59, in process_gamestate
  File "stellarisdashboard\parsing\timeline.py", line 109, in _process_gamestate
  File "stellarisdashboard\parsing\timeline.py", line 2365, in extract_data_from_gamestate
  File "stellarisdashboard\parsing\timeline.py", line 2366, in <listcomp>
  File "stellarisdashboard\parsing\timeline.py", line 2366, in <genexpr>
IndexError: list index out of range`

This has made it so that the dashboard will no longer record any of my progress after 2380. What can I do to resolve this?

**Comment by eliasdoehne** [comment]
Hi @MrFunEGUY , sorry, I was unable to work on the dashboard for some months. Do you still have this error and would you be able to share a save file for it?

**Comment by MrFunEGUY** [comment]
> Hi @MrFunEGUY , sorry, I was unable to work on the dashboard for some months. Do you still have this error and would you be able to share a save file for it?

No worries, this is from a long time ago and i don't really have the info from then. Next time I get something like this, I'll let you know again, with logs.

**Comment by MichaelMakesGames** [comment]
There have been many changes since this was reported. Closing this for now. If you encounter this again, feel free to re-open
