### ISSUE TITLE
Dashboard stuck at matplotlib.font_manager - INFO - generated new fontManager

### ISSUE THREAD

**Issue by uspesnymekkys** [eliasdoehne/stellaris-dashboard#109]
Hey, it seems that my fresh Dashboard install gets stuck at... whatever the process mentioned in the title is. After that, it doesn't really do anything, much less parse any saves. To be fair, my game is modded quite a bit, although no mods should be messing with fonts. I added the output of Dashboard. If anything else would be necessary, I'll gladly add it. Thanks much for your help!

[Dashboard output.txt](https://github.com/eliasdoehne/stellaris-dashboard/files/11525713/Dashboard.output.txt)

**Comment by eliasdoehne** [comment]
Hi @uspesnymekkys, can you confirm if the stellaris save files actually exist in the shown directory? `C:\Users\vinte\Documents\Paradox Interactive\Stellaris\save game`. 

If you play the game while the dashboard program is running, you should see some output there that it has found some files.

However, I also think that the most recent stellaris update broke some other parts of the dashboard, so I would expect it to still fail... I am planning to take a look at that today or tomorrow.

**Comment by uspesnymekkys** [comment]
Okay, so apparently my documents directory was named in Czech which the computer didn't like. I renamed it and now it works. Thanks for your time.
