### ISSUE TITLE
Help with *nix Installation

### ISSUE THREAD

**Issue by 7ranceaddic7** [eliasdoehne/stellaris-dashboard#12]
I (hopefully) followed instructions for Linux install (Ubuntu 18.04).

The last command (stellarisdashboard) is generating an error:

(env) scott@Jupiter:~/.local/share/Paradox Interactive/Stellaris/stellaris-dashboard$ stellarisdashboard
bash: /home/scott/.local/share/Paradox Interactive/Stellaris/stellaris-dashboard/env/bin/stellarisdashboard: "/home/scott/.local/share/Paradox: bad interpreter: No such file or directory

**Comment by eliasdoehne** [comment]
Hi, sorry for the late response! Thanks to Clothlen for your detailed instructions. 

In the latest release of the dashboard, an simpler alternative is to use `pip install -r requirements.txt` and then simply run `python -m stellarisdashboard` from the main directory, i.e. it is no longer necessary to install the dashboard with setup.py.

Let me know if you experience more problems, for now I will update the installation instructions in the readme and close the issue.
