### ISSUE TITLE
Error while reading save file - expected literal or { token for composite object or list

### ISSUE THREAD

**Issue by aitch-hat** [eliasdoehne/stellaris-dashboard#14]
See full error as well as save state attached. (Save state changed from .sav to .zip in order to upload.)
![dashboard-error](https://user-images.githubusercontent.com/20600979/52337392-69352280-29ff-11e9-8ec8-f6c792b7d659.JPG)
[autosave_2321.01.01.zip](https://github.com/eliasdoehne/stellaris-dashboard/files/2836045/autosave_2321.01.01.zip)

**Comment by eliasdoehne** [comment]
Hi, thanks for your bug report. The following line (556843) in your save file causes the issue:

`
		policy_flags={
			unrestricted_wars orbital_bombardment_indiscriminate first_contact_attack_allowed border_policy_closed name = food_policy_gestalt_rationing eac_apm_habitability_60 eac_apm_eligibility_overcrowded_unemployed eac_apm_force_migrate_none interference_full enlightenment_not_allowed 
		}
`

Note the `name = food_policy_gestalt_rationing` in the middle.

Did you use any other mods for this save file? Especially ones that might add new policies to the game?

**Comment by aitch-hat** [comment]
Many thanks for your quick response! I do have about 20 mods installed. I did a search through my mod files and the only mod that contains the string "food_policy_gestalt_rationing" is Glavius's Ultimate AI. I'll let the relevant person know!

Many thanks for your help.

**Comment by eliasdoehne** [comment]
Sure no problem! Yea, it might be a problem with Glavius' mod. Maybe the extra "name" and "=" strings in the list are ignored by the game. Seems plausible at least.

Let me know if you find any other issues!
