### ISSUE TITLE
save reading speed

### ISSUE THREAD

**Issue by Latuninix** [eliasdoehne/stellaris-dashboard#15]
Hello,
i found the issue while stellaris is saving and the dasboard tries to read the save file. Because the game still not finished saving, because the game engine sucks and the dashboard is very quick, i got the message "bad zip file".
My suggestion: add a retry system after around 0.5 to 1 seconds. I am at the middle game and around 70 % of my savefiles are not being read.

**Comment by eliasdoehne** [comment]
Hi Latuninix, 

thanks for your bug report! 

I think this is a good suggestion. I think I will either add such a retry mechanism, or perhaps more simply a configurable delay before a save file is parsed. Might happen over the next weekend :)

**Comment by eliasdoehne** [comment]
I made a new release that should hopefully resolve this issue. 

You can now specify the number of attempts for reading a broken save file, as well as the delay between attempts, in the dashboard settings page.

**Comment by eliasdoehne** [comment]
For now I will close the issue, feel free to reopen it or make a new one if you experience any further problems!
