### ISSUE TITLE
Maximum Recursion Depth Reached

### ISSUE THREAD

**Issue by ApproachingApathy** [eliasdoehne/stellaris-dashboard#16]
When attempting to read my save state i get the following error:

RecursionError: maximum recursion depth exceeded
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "stellarisdashboard\save_parser.py", line 126, in get_gamestates_and_check_for_new_files
  File "multiprocessing\pool.py", line 657, in get
RecursionError: maximum recursion depth exceeded

**Comment by eliasdoehne** [comment]
Hi ApproachingApathy,
 thanks for the bug report! I will look into it as soon as I can, but it might take a few days.

**Comment by ApproachingApathy** [comment]
No problem, thanks for work you put into this. This is definitely something the game could use.

**Comment by eliasdoehne** [comment]
Before I start looking into it I have a few basic questions: 

  - Does this happen every time or did it use to work but started producing these errors?
  - Are you using the latest release version? 
  - Can you send me a screenshot with the full error message? I think there might be some more info above that. If the error is reproducible could you send me a save file that causes it? You can email me: blubblubblobb at gmail dot com

**Comment by ApproachingApathy** [comment]
I only started using the mod recently, but it did work for a while. It stopped working within the same play session. Issue occurs every time the an autosave occurs. (It's set to read monthly)

I am using the 0.4 beta. I am also playing with mods.

I hope this will do for the error: [pastebin](https://pastebin.com/ymB1gYVj).

I uploaded the save file here, I can send it to your email if you'd like.
[autosave_2245.02.01.zip](https://github.com/eliasdoehne/stellaris-dashboard/files/2969163/autosave_2245.02.01.zip)

**Comment by Latuninix** [comment]
I think it's the same issue like my issue. The save is not completed while the Dashboard is reading the file so it's rapidly crashs.

**Comment by eliasdoehne** [comment]
Thanks, I will take a look now

**Comment by eliasdoehne** [comment]
Your save contains a "Surveyor Probe" object that is nested ~1000 levels deep. Are you using some kind of mod?

```
name="Surveyor Probe"
fleet_template=51
action_initialized=yes
actions={
    find_system={
        data={
            trigger="mem_surveyor.vanilla.1"
            found_system={
                move_to=this
                wait=1.000
                effect="mem_surveyor.vanilla.2"

            }
            failed={
                wait=10.000
                find_system={
                    trigger="mem_surveyor.vanilla.3"
                    found_system={
                        effect="mem_surveyor.vanilla.4"

                    }
                    failed={
                        effect="mem_surveyor.vanilla.5"

                    }
                    method=random
                }

            }
            method=closest
        }
        scope={
            type=fleet
            id=161
            random={ 0 3260466031 }
            from={
                type=fleet
                id=161
                random={ 0 249682727 }
                from={
                    type=fleet
                    id=161
                    random={ 0 3186938791 }
                    from={
                                   ... ~1000 more levels of this ...
                            }
                        }
                    }
                }
            }
        }
        system=671
        index=0
        current={
            move_to={
                coordinate={
                    x=0.000
                    y=0.000
                    origin=671
                }
            }
        }
    }
}
```

**Comment by eliasdoehne** [comment]
Actually, I just tried loading the save and my game crashed.... At this point I am tempted to consider this a bug in the game (or mod)

:-/

**Comment by ApproachingApathy** [comment]
Yes, I did mention I was playing modded. So that's the issue. Thanks for looking into it and sorry for wasting your time.

**Comment by eliasdoehne** [comment]
Hi, no worries at all. Sorry, I missed the mod part in your message.

I could rewrite the parser to avoid the recursion, but this will take a lot of work which I don't have much time for at the moment. But I will leave this issue open for when I have a bit more time.

**Comment by Nephos** [comment]
HI @eliasdoehne , maybe if you leave me some indications/help about how you structured the parser, I could give a hand on this !

**Comment by eliasdoehne** [comment]
@Nephos Sorry for the late response... Unfortunately I don't think it is an easy thing to fix :-( 

The whole parser is written recursively and I think it would probably be pretty rough to rewrite it. (In fact I'm pretty sure that it is the oldest code in the entire repo) If you still want to take a look, this function is the entry point for the parser, you can pass it a filename to a Stellaris `.sav` file:

https://github.com/eliasdoehne/stellaris-dashboard/blob/004713975cd555249ce61ffc34105f0fc0bbd998/stellarisdashboard/parsing/save_parser.py#L256

I am closing the issue for now, on the off chance that you're still interested in it, please feel free to comment and I'll reopen it!

**Comment by eliasdoehne** [comment]
(of course maybe it wouldn't be as bad as I imagine right now but I am always worried about old code :D)
