### ISSUE TITLE
Potential Memory Leak?

### ISSUE THREAD

**Issue by EclipsedStar0** [eliasdoehne/stellaris-dashboard#163]
(Apologies if this isn't exactly in the desired format for issues)
I'm not entirely certain how to reproduce this, but I've noticed an excessivly large amount of memory (Roughly 22 GB worth as the baseline was around 9/10ish GB and the computer has a max of 32GB) being used up by Stellaris Dashboard when running. It's hard to quantify because I don't have really have any metrics to go off of besides the current memory being used by the computer before/during/after, but I've noticed that while memory usage increases some while parsing saves-- **normally** I notice it falling back down when it starts on the next save, but sometimes it doesn't-- and it just slowly becomes a race to the computer's maximum memory and then the program just grinds to a halt, not continuing on nor terminating itself, but still holding all of that memory until it's manually terminated (and then the second it is, memory usage drops all the way down to it's 'baseline' (what it was before the program was run) and everything runs smoothly once more). Now, while inconvienant when parsing saves (which is something you'd normally only do once, the first time you use Stellaris Dashboard or if you haven't used it in a while), the issue is that this memory-problem also appears to be present when the Dashboard recieves a new save game to parse from Stellaris-- which winds up slowly draining memory until everything pretty much grinds to a halt and you're forced to terminate Stellaris Dashboard.

Again-- I'm not sure why this is, nor do I have any metrics to go off of, but there _seems_ to be some sort of memory issue with the program, at least on my end/to my eyes.

**Comment by SamFonss** [comment]
Same issue here, ramped up to 24gb memory usage as it ran, culminating in me being unable to continue playing the game.

**Comment by MichaelMakesGames** [comment]
I'll have time to take a look this weekend

**Comment by MichaelMakesGames** [comment]
This will be fixed in the 6.4 release
