### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by Romanophile** [eliasdoehne/stellaris-dashboard#164]
Issue with parsing, happens on a specific day and parses files fine before date. 
[2270.03.11.sav.zip](https://github.com/user-attachments/files/17876113/2270.03.11.sav.zip) - Save Parses Fine.
[2270.03.12.sav.zip](https://github.com/user-attachments/files/17876114/2270.03.12.sav.zip) - Save does not Parse.
 Game is modded, here is the list.
[Trimmed.json](https://github.com/user-attachments/files/17876153/Trimmed.json)

note: removing my own country from the game fixes the issue.
note2: Figured out the problem, some kind of issue with using the nanofabrication starbase building from the technology ascendent mod.

**Comment by MichaelMakesGames** [comment]
Reopening this, because I'd like the dashboard to handle modded games (at the very least, not crash or fail to parse)

**Comment by MichaelMakesGames** [comment]
This will be fixed in the 6.4 release
