### ISSUE TITLE
problems with updating database

### ISSUE THREAD

**Issue by Latuninix** [eliasdoehne/stellaris-dashboard#17]
Hello,
I installed the newest version and now the database is not anymore being updated, or like this.

i attached a file with the log

[log.txt](https://github.com/eliasdoehne/stellaris-dashboard/files/2975715/log.txt)

with older versions it works fine

**Comment by eliasdoehne** [comment]
Hi, does the same problem happen when you start a new game?

If you want you can send the database and a save file to blubblubblobb at gmail dot com and I will take a look.

**Comment by Latuninix** [comment]
Hi,
sorry for the late answer. I made a new game and actually there is no problem.

I think it's a one time error from my game or something like that. Sorry for wasting your time

**Comment by eliasdoehne** [comment]
Hey Latuninix, 

There is absolutely no need to be sorry.  For me it's always really great to hear that people are using the program and bug reports are especially helpful :)

It's great that it works now, please let me know if there are any problems in the future!
