### ISSUE TITLE
Leader reading problem

### ISSUE THREAD

**Issue by Latuninix** [eliasdoehne/stellaris-dashboard#18]
Hey,
I found an issue at my current gameplay. After winning a war with my allies there is a problem while processing "leaders".

I attached a zip file with the latest save and the log. I play with mods but this dont effect the leader category, removing the mods dont helped.
[file.zip](https://github.com/eliasdoehne/stellaris-dashboard/files/3090864/file.zip)

**Comment by eliasdoehne** [comment]
Sorry for the very late response. I think I fixed this problem at the time. If it still persists, please feel free to comment and we'll reopen the issue.
