### ISSUE TITLE
Dashboard Accessibility for the VIsually Impaired/Blind

### ISSUE THREAD

**Issue by BlindGuyNW** [eliasdoehne/stellaris-dashboard#21]
It would be great if the dashboard had some more accessibility for the visually-impaired, or folks who use screen reader technology in general. Right now, the events list is mostly readable, but filters are a little hard to use, and the graphical displays are practically impossible.

Ideally, anything communicated graphically could also be viewed in an equivalent data table. If needed, I can provide web accessibility expertise, though I'm not familiar with the dashboard code yet.

As a blind player just getting into Stellaris, the dashboard promises to be invaluable, and it would be wonderful to see a few tweaks added to make it more pleasant to use.

**Comment by eliasdoehne** [comment]
Sure, I could add another rest endpoint that we could customize for accessibility.

I could for example add some ledger tables that list the recent numbers from the graphs.

Maybe you could also compile a list of the things in the game that are the most difficult for you and I could then see what's possible to add.






On August 9, 2019 3:07:53 AM GMT+02:00, Zachary Kline <notifications@github.com> wrote:
>It would be great if the dashboard had some more accessibility for the
>visually-impaired, or folks who use screen reader technology in
>general. Right now, the events list is mostly readable, but filters are
>a little hard to use, and the graphical displays are practically
>impossible.
>
>Ideally, anything communicated graphically could also be viewed in an
>equivalent data table. If needed, I can provide web accessibility
>expertise, though I'm not familiar with the dashboard code yet.
>
>As a blind player just getting into Stellaris, the dashboard promises
>to be invaluable, and it would be wonderful to see a few tweaks added
>to make it more pleasant to use.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/eliasdoehne/stellaris-dashboard/issues/21

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by h-rezaei** [comment]
Hey, I'm the author of this topic:
https://steamcommunity.com/workshop/filedetails/discussion/1466534202/1639793203764027492/
I also agree that focusing on the ledger would be a better option, It's raw text and anything that's added could be then easily read.

**Comment by BlindGuyNW** [comment]
I tend to agree. There is actually a built-in alert for hostile fleets in system, which centers  the map on them, but generally the more info we can get about what is in a system the easier it will be for us I think. The downside to asking for potentially real time information is that it’s obviously going to be at least a little bit out of date, but I figured that stuff that is relatively static would be easier to grab.

**Comment by h-rezaei** [comment]
I have compiled a list of things, BlindGuyNW feel free to refine and add to them please.
In a little bit of higher priority is system details such as  resources, structures, wormholes, stations that i think would be great if they could be added to the system browser. Right now it shows a list of planets, hyperlanes and owner.
Planet modifiers, This one is a little bit of hard to detect with our current setup so i think it would be very great if when the planets table is added, we also  get to see the modifiers.
Planet info, such as pops/crime/housing, maybe also jobs and buildings and districts only if possible.
Lower priority, list of researched tech. The existing ui in game is very crowded but nevertheless, OCR still works on it.

**Comment by BlindGuyNW** [comment]
I think there isn't much to refine, I agree with @h-rezaei. THe only thing which occurs to me is a way to see complete lists of, say, leaders or traditions or whatever. At the moment as far as I can see it's all a bit piecemeal depending on what you select.

I was also wondering about the event filters. ARe they actually supposed to be links or do they have some other interaction that I'm not seeing? WHen I click on them they don't actulaly seem to do much with the visible ledger, but I'm not quite sure if it's a screen reader problem.

**Comment by eliasdoehne** [comment]
Ok thank you, I will start on some of these features, hopefully this weekend.

Event filters are buttons that trigger some Javascript which toggles visibility of the elements. This is to hide some events that happen a lot more often than others or which might not be as interesting. Let me know if there's a better solution, I don't have much experience with frontend development. Any help there would of course be appreciated :)

**Comment by h-rezaei** [comment]
Hey. I have updated my list that's posted above. We've found out that finding trade value of a system is also a little problematic so i added that to our wishlist as well.

**Comment by eliasdoehne** [comment]
Hi, I am already working on some of this stuff and already started to add pages for planets listing modifiers, deposits, blockers, districts and buildings. It kind of works but I need to test it some more and fix some issues before I can make a new release.

Unfortunately, it will still take some time, as I am away from my computer for a few days. Just wanted to give a small update.

**Comment by h-rezaei** [comment]
Thank you very much for your work, I almost check this project every day for updates, I can't play the game without it anymore because of the system viewer that it has, It basically makes the galaxy map accessible to us, I hope you'll be able to also improve that part of the mod. I currently  have a notepad file with the list of systems that i own, and i manually add info such as the stations that i built there and if there are special resources that i have to  extract later.
I'm thinking to avoid trade routes and trade value completely until your mod supports showing it for the systems in the future. There's a mod that appears to disable pirates, i have enabled it, i'll see if i get any pirates spawning. here's the link to the mod if anyone's interested:
https://steamcommunity.com/sharedfiles/filedetails/?id=1586735803

Planet's info would be very useful  when we control high amount of colonies, Excited to see how it works when it gets released!

**Comment by h-rezaei** [comment]
Hey, I was wondering if you've forgotten about this or just have not found the time to work on it

**Comment by eliasdoehne** [comment]
Hello, apologies for getting back to you so late. I have not forgotten about this, but have been very busy IRL lately which left with no energy for programming in the evening after work. I hope that my situation will normalize soon, allowing me to continue working on the Dashboard.

**Comment by eliasdoehne** [comment]
@BlindGuyNW @h-rezaei 

I made a new release with at least some of the features you mentioned:
https://github.com/eliasdoehne/stellaris-dashboard/releases/tag/v0.6.0

Specifically, I added planet pages that list deposits, buildings, districts, blockers and planet features and I also extended the System pages with Gateway and Wormhole destinations. (I hope this part works, I could not test it very much 😨)

I rushed this a bit because my free time is very limited at the moment, I hope that it has not too many bugs... I know this only covers a few of the features, but maybe it'll give some improvements to your game.

Feel free to report any bugs or issues that you find.

**Comment by h-rezaei** [comment]
This is amazing! Thank you very much, I will test this and will let you know! Also got excited to see battle logs are also a thing now.

**Comment by h-rezaei** [comment]
Hi there
I have not forgotten about this thing.
Really sorry if we did not submit any feedback on your work. stellaris change ui positions, and something about 500 to 1000 mouse positions became none functional for us. I am going to get a sighted person to help me fix it, but it takes a bit of more time because of the number of positions we need to save again.

**Comment by h-rezaei** [comment]
Hello there!
sorry for the spam
I have tested the new features!
The planet screen works, list of blockers and districts is extremely helpful!
List of buildings is a little bit weird, I can't seem to understand it, I have something like: Buildings:0: 1, 1: 1, 116: 1, 2: 1, 3: 1, 4: 1

regarding systems: I can see gateways now, and i can see resource deposits! I haven't seen any special deposits yet, I think i haven't found any, The gateway/wormhole is super super helpful, IF i'm not mistaking, there's no way for us to detect that with OCR.

I had another request, for whenever you had time of course,
Do you think it's possible to add the list of constructions in each systems?
e.g. starbases, megainstallations, dlc constructions, etc.
I will explain the reason behind this, but i had also another request, is it also possible to list the fleets in the systems?

The reason for asking these is that while i can  find out where my fleets and starbases at by using the outline and double clicking on them, There's no way for me to find out where the enemy fleets are at, if they're camping in any of my systems. I get a notification when they invade, but after that they can go anywhere in my systems and i can lose  where they are.
Same goes for starbases, Finding AI starbases is is also very hard.
Do you think these are possible to do as well?
I love this add on now, I can't really play the game  without it, I used to open a notepad and write each system and its links to each other, + any constructions that were in them, now this addon does it all for me.

**Comment by eliasdoehne** [comment]
Awesome, glad to hear that it's useful!

Regarding
> List of buildings is a little bit weird, I can't seem to understand it, I have something like: Buildings:0: 1, 1: 1, 116: 1, 2: 1, 3: 1, 4: 1

I will have to check that, when I first built that feature it would show something like "research lab 1: 1" or similar, where the first number is the tier of the building and the second is how many of those buildings are on the planet. I'll try to take a look this week, often the structure of save changes a bit, especially with major updates

**Comment by h-rezaei** [comment]
Hey, i had two questions.
1. IS there an existing feature to see battle logs in your mod? e.g. the damage output percentages that's shown after a fight.
2. Do you know why the filters in the event ledger don't work for me? e.g. when i click on colonization, it still shows me all the log, and does not filter them to colonizations only.
thanks!

**Comment by h-rezaei** [comment]
Hello there!
Do you think it's possible you add surveyed_by in the system view as well?
which would show which empires surveyed the system i'm looking at?
I am mainly wanting this cause i keep forgetting which systems i surveyed and the map shows them as colors.
Thanks!

**Comment by eliasdoehne** [comment]
Sorry for the late reply.
> Do you know why the filters in the event ledger don't work for me? e.g. when i click on colonization, it still shows me all the log, and does not filter them to colonizations only.

The buttons work by toggling `elements[i].style.display` in Javascript. They definitely work for me. Could it be that the text is still visible to the screenreader? Sorry, I don't know anything about that and also not much of a Javascript expert :-/

>  Do you think it's possible you add surveyed_by in the system view as well?
I can try to add this for the next release. I know that the save files maintain for each country a list of visible and surveyed systems, so it should be doable. I might add some option in the settings to disable some of these by default, but I will make it very clear when I do so.

**Comment by MichaelMakesGames** [comment]
This issue is several years old and I'm not sure of the status, so I'm closing it.
Please open up separate issues for concrete improvements, or brainstorm/discuss generally in Discussion #138: Accessibility feedback and improvements
