### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock' in Python 3.8

### ISSUE THREAD

**Issue by sinker1345** [eliasdoehne/stellaris-dashboard#25]
Apparently time.clock has been deprecated since Python 3.3 from what I read. I replaced all instances of time.clock() with time.process_time() in timeline.py and now I no longer receive an error when processing saves and I can view save data in chromium.

**Comment by eliasdoehne** [comment]
You're right, until now I used Python 3.7 to test and build the project, so I didn't notice this issue before. I'll merge your PR.
