### ISSUE TITLE
Zenith of Fallen Empires compatability

### ISSUE THREAD

**Issue by Oikio** [eliasdoehne/stellaris-dashboard#27]
Looks like dashboard cannot interpret empires data when they become ascendant.

Thank you for the app, btw, it's very useful!

**Comment by eliasdoehne** [comment]
Sorry for responding very late. Could you perhaps upload two savefiles, one before and one after ascending?

Then I can check if it would be difficult to add support.

**Comment by Oikio** [comment]
It was quite a while since I've played Stellaris last time. Don't even have it installed ATM. I will close bug, doesn't look like it's bothering anyone besides me.
