### ISSUE TITLE
Great Application - minor improvements

### ISSUE THREAD

**Issue by IslayTzash** [eliasdoehne/stellaris-dashboard#28]
It's a great addition to the game and I didn't have any problems using it with 2.7.1.

Is there any way to make it faster or add a "load in progress" overlay?  I tend to click a lot of stuff and there's a major backlog of events.   Each click takes about 2s (500ms for the request + 1.5s for the JS to update).   I was only playing with 4 empires on a tiny map.   I assume it gets much worse for a larger game.

The timeline slider on the bottom only appears to be good for the galaxy map tab.   Would it make sense to only display it on that tab?   And maybe add custom "Marks and Steps" to the dcc.Slider?  It recognizes key presses left arrow and right arrow but they don't really move it to anything interesting.   I'd really want it to jump to a time when the map changed which might require some backend smarts to render a list of marks and steps, but at least it could skip times where there is no game data snapshot.

**Comment by eliasdoehne** [comment]
Hi @IslayTzash, thanks for your comment, you make a lot of good points.

I agree that the speed is a big issue. Maybe I can improve how data is loaded into memory, or perhaps having so many graphs is too much for the framework. I will think about this & experiment. Let me know if you have any suggestions

About the timeline slider, I also agree with your points. Right now the slider is currently defined globally, I remember this being the simplest solution at the time I didn't have the patience to look deeper. I think when I started the dashboard, tabs were an experimental feature in Dash, so very possible there are better ways to do things now. 
(of course if you see a way to do it feel free to make a pull request)

**Comment by eliasdoehne** [comment]
I added some thoughts on how you can configure the dashboard for better performance to the readme:

https://github.com/eliasdoehne/stellaris-dashboard#how-to-improve-performance

While I expect it will still be rather slow if you click rapidly, maybe it will help make the application a bit more responsive.

I'll close the issue for now but can reopen if there is more to be done.
