### ISSUE TITLE
Escaped quotes in string fields not properly escaped

### ISSUE THREAD

**Issue by HiddenKn** [eliasdoehne/stellaris-dashboard#3]
```species_bio="The defining moment of Xarmiri history came two centuries ago when the Pasceal Kingdom, an aquatic civilization that ruled the ocean floor of their shared home planet, invaded the surface in an attempt to prevent Xarmiri industry from damaging their oceans. The result was a genocidal war that decimated the Xarmiri civilization and forced the survivors to flee in hastily-designed starships, leaving the Pasceals in total control of the planet. The refugees eventually settled on an oceanic world they dubbed \"New Xarmir\" and slowly rebuilt their species. Though not aggressive by nature, the loss of their homeworld badly traumatized the Xarmiri. They will go to any length to take it back."```

This string causes the script to throw the error: 

```File "E:\Users\Alice\Documents\git\stellaris-dashboard\src\stellarisdashboard\save_parser.py", line 211, in _parse_key_value_pair
f"Line {eq_token.pos}: Expected = token, found {eq_token} (key was {key_token})"
stellarisdashboard.save_parser.StellarisFileFormatError: Line 1: Expected = token, found Token(token_type=<TokenType.STRING: 6>, value=' and slowly rebuilt their species. Though not aggressive by nature, the loss of their homeworld badly traumatized the Xarmiri. They will go to any length to take it back.', pos=1) (key was Token(token_type=<TokenType.STRING: 6>, value='New', pos=1))
```

I tried changing the ```Q_STR``` regex to ```"((\\\")|([^"]))*"``` to try to fix it but that didn't work. Let me know if you need any other information.

**Comment by eliasdoehne** [comment]
Yes I did not think of this when I wrote the program. I don't know when I will have time to fix this, if you find a solution let me know! Can you also check if you are using the token_value_stream_re.py tokenizer or the cython_ext/token_value_stream.pyx one? 

If you are using the regex based one, you should see a warning like 

`2018-03-25 15:34:31,542 - stellarisdashboard.save_parser - INFO - Cython extensions not available, using slow parser. Error message: "cannot import name 'token_value_stream'"`

**Comment by HiddenKn** [comment]
Added a PR with a fix for the Cython version.

**Comment by HiddenKn** [comment]
This might need to be reopened for the non-cython version?

**Comment by eliasdoehne** [comment]
Oh the merge for the cython version auto-closed it apparently. (I'm not too familiar with Github yet)

Thanks for your contribution by the way!

**Comment by HiddenKn** [comment]
No problem :)

**Comment by eliasdoehne** [comment]
Should now be fixed in the re-version, too.
