### ISSUE TITLE
Dashboard crashes at 'get_leader_name'

### ISSUE THREAD

**Issue by pyroraptor07** [eliasdoehne/stellaris-dashboard#39]
Dashboard.exe crashes at 'get_leader_name' while trying to parse the latest save file for my new playthrough. parse_saves.exe also crashes when trying to process saves with the same empire.
[stellaris-dashboard-output.txt](https://github.com/eliasdoehne/stellaris-dashboard/files/5542298/stellaris-dashboard-output.txt)
[democraticentheriunion3_-761093633.zip](https://github.com/eliasdoehne/stellaris-dashboard/files/5542300/democraticentheriunion3_-761093633.zip)

**Comment by pyroraptor07** [comment]
Changing the empire to a different name list seems to work.

**Comment by MichaelMakesGames** [comment]
Closing this. There have been lots of changes, especially to localization, since this was reported
