### ISSUE TITLE
graphs for market prices?

### ISSUE THREAD

**Issue by hifiguyy** [eliasdoehne/stellaris-dashboard#62]
Hey just wondering if there is a way to enable tracking of the market prices with this and maybe see who is buying/selling (if the AI does that lol).

Cheers.

**Comment by eliasdoehne** [comment]
Hi @hifiguyy , I tried to do this once, but the way market prices are encoded in the save files is not very obvious and at the time I did not have the patience to figure it out last time I looked into it.

**Comment by Francokab** [comment]
> Hi @hifiguyy , I tried to do this once, but the way market prices are encoded in the save files is not very obvious and at the time I did not have the patience to figure it out last time I looked into it.

Hi, I've looked into it and I think it is encoded as follow : 
- fluctuations describe how much each ressource deviate from it's normal price by following this formula
    - actual_price = base_price*(1+fluctuation/100)*(1+- market_fee)
    - acording to the wiki, the maximum and minimum fluctuation should be 400 and -80
    - the ressources are in the order stated bellow
- galactic_market_resources describes resources that are currently available in the galactic market in this order
    - I don't know and probably not available
    - Energy credit
    - Minerals
    - Food
    - I don't know and probably not available
    - I don't know and probably not available
    - I don't know and probably not available
    - I don't know and probably not available
    - I don't know and probably not available
    - Consumer Goods
    - Alloys
    - Volatile motes
    - Exotic gases
    - Rare crystals
    - Living metal
    - Zro
    - Dark matter
- I haven't checked what how the things look before the galactic market is created 

I think that should be enough to implement a graph that track the price of each resources but I haven't really looked into how the dashboard work and I'm lazy so if someone wants to implement it, it would be cool.

**Comment by eliasdoehne** [comment]
Hi Francokab, thanks for checking that! I'll make another attempt then :+1:

**Comment by eliasdoehne** [comment]
I just made another release with market price graphs, thanks for the help and the suggestions!
