### ISSUE TITLE
Star Trek: New Civilization Compatibility

### ISSUE THREAD

**Issue by bestekov** [eliasdoehne/stellaris-dashboard#69]
Mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1886496498

Started a new game as United Earth on Large galaxy, otherwise default settings.

Error parsing save that then crashes the entire dashboard app:
```
MainProcess - 2022-07-15 00:12:48,895 - stellarisdashboard.parsing.timeline - INFO - unitedearth_-301316477 2150.01.05 Adding new game unitedearth_-301316477 to database.
MainProcess - 2022-07-15 00:12:48,896 - stellarisdashboard.parsing.timeline - INFO - unitedearth_-301316477 2150.01.05   - Processing systems
MainProcess - 2022-07-15 00:12:48,985 - stellarisdashboard.parsing.timeline - ERROR - unitedearth_-301316477 2150.01.05 Rolling back changes to database... Traceback (most recent call last):
  File "stellarisdashboard\parsing\timeline.py", line 59, in process_gamestate
  File "stellarisdashboard\parsing\timeline.py", line 109, in _process_gamestate
  File "stellarisdashboard\parsing\timeline.py", line 283, in extract_data_from_gamestate
ValueError: Multiple starbases in 27 {'coordinate': {'x': -52.632, 'y': -371.75, 'origin': 4294967295, 'randomized': 'yes'}, 'type': 'star', 'name': {'key': 'Rex Callina'}, 'planet': [600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611], 'star_class': 'sc_g', 'hyperlane': [{'to': 871, 'length': 61}, {'to': 885, 'length': 59}, {'to': 109, 'length': 23}, {'to': 108, 'length': 18}, {'to': 868, 'length': 30.52635}], 'asteroid_belts': [{'type': 'rocky_asteroid_belt', 'inner_radius': 750}], 'flags': {'voth_homeworld': 62376000}, 'initializer': 'voth_homeworld', 'fleet_presence': [0, 779, 926, 927, 928, 929, 930], 'inner_radius': 335, 'outer_radius': 435, 'starbases': [64, 72], 'trade_hub': {'collected': 35.39496, 'collected_from': [27]}, 'trade_collection': {'targets': [{'target': 27, 'distance': 0}]}, 'trade_piracy': {'throughput': 0, 'total': 0, 'max': 0, 'active': 0, 'used': 0, 'targets': [{'target': 27, 'distance': 0}]}, 'sector': 48}
MainProcess - 2022-07-15 00:12:48,989 - stellarisdashboard.dashboard_app.visualization_data - WARNING - Warning: Game unitedearth_-301316477 could not be found in database!
Traceback (most recent call last):
  File "stellarisdashboard\__main__.py", line 32, in <module>
  File "stellarisdashboard\__main__.py", line 24, in main
  File "stellarisdashboard\cli.py", line 84, in f_monitor_saves
  File "stellarisdashboard\dashboard_app\visualization_data.py", line 90, in get_current_execution_plot_data
  File "stellarisdashboard\dashboard_app\visualization_data.py", line 199, in update_with_new_gamestate
  File "stellarisdashboard\datamodel.py", line 354, in get_gamestates_since
  File "sqlalchemy\orm\query.py", line 2865, in one
    return self._iter().one()
  File "sqlalchemy\engine\result.py", line 1408, in one
    return self._only_one_row(
  File "sqlalchemy\engine\result.py", line 562, in _only_one_row
    raise exc.NoResultFound(
sqlalchemy.exc.NoResultFound: No row was found when one was required
[26620] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by eliasdoehne** [comment]
Hi @bestekov, generally, I cannot promise compatibility with other mods especially if they change some assumptions I made based on the main game.

But I would be happy to take a look if you could somehow share 1-2 save files that cause this error to happen, if I can fix it without rewriting too many things I will definitely do it.

**Comment by bestekov** [comment]
Sure thing! Here are some save
[unitedearth_-301316477.zip](https://github.com/eliasdoehne/stellaris-dashboard/files/9133718/unitedearth_-301316477.zip)
s

**Comment by bestekov** [comment]
Modlist for the above saves

![2022-07-18_123821](https://user-images.githubusercontent.com/4909619/179560294-067a044c-5b4d-4097-9f23-4c1296d38c22.png)

**Comment by bestekov** [comment]
> Edit: Actually on a second glance, it seems like your error could be related to this #70
> 
> Still, it would be helpful to have a save file so I can try to reproduce it on my end

Oh! Good call! Yes that looks like the same bug.

**Comment by eliasdoehne** [comment]
Hello, I made another release that should hopefully fix this problem, it was related to the orbital ring megastructure introduced in the Overlord DLC that works like a starbase in the game.

**Comment by bestekov** [comment]
That fixed the save_parse issue!

Though there is a new weird issue... all the country names show up as `Format.devorian solidarity ( 40 )`:
![2022-07-24_115823](https://user-images.githubusercontent.com/4909619/180655814-b925bdf4-7c4c-4412-891f-30532e73563d.png)

**Comment by eliasdoehne** [comment]
The names showing up like that is probably related to the localization changes that were introduced in the last Stellaris patch. To display them correctly requires a bit of work if you use mods that modify or extend the name lists:

https://github.com/eliasdoehne/stellaris-dashboard/blob/master/README.md#names-and-localizations

Let me know if that works.

I'm actually not sure why I added the number in parentheses after the names, but it's the in-game ID of the country in question. I will probably make another release that removes this or makes it configurable.

**Comment by eliasdoehne** [comment]
Actually I decided to test it locally, I collected files from:
- .../steamapps/common/Stellaris/localisation/english (base game)
- .../steamapps/workshop/content/281990/1886496498/localisation/english (mod, not sure if the path will be the same for you)

and your save now shows up ok for me:
![image](https://user-images.githubusercontent.com/3602589/180656780-4d4a2886-e5eb-4464-b898-b5394b5c18b3.png)

**Comment by bestekov** [comment]
Amazing! I'll give that try. Thank you so much for your help and awesome work on this mod!
