### ISSUE TITLE
Mod giving error when parsing savefiles

### ISSUE THREAD

**Issue by MethodOfMadness** [eliasdoehne/stellaris-dashboard#71]
Hi,

replying to the Steam discussion here, so I can attach savefiles.  I set the number of threads to one and re-ran "parse-saves.exe" so that the log is a bit easier to read (full result: [parse_saves console output.txt](https://github.com/eliasdoehne/stellaris-dashboard/files/9145072/parse_saves.console.output.txt) ).  I'm also attaching the latest autosave, which you can see in the log can't be processed.  Let me know if I should try to find an earlier savefile from the same campaign which can be parsed (I have some other ones stored in the steam cloud).

Also, FYI, as said in the steam comments, I did open the database file to export some data, but as far as I know, no changes were made.  I used "DB Browser for SQLite" 3.12.2 (64-bit) to access the file.  Also, it looks like the mod _did_ add some entries to the database after I exported things, so I doubt the access caused issues.

zipped savefile: [autosave_2331.01.01.zip](https://github.com/eliasdoehne/stellaris-dashboard/files/9145077/autosave_2331.01.01.zip)

Thanks for looking into this :)

**Comment by eliasdoehne** [comment]
Perfect, thank you! I will take a look some time this week (probably tomorrow or Friday)

**Comment by eliasdoehne** [comment]
Hello @MethodOfMadness , I just made a new release that should fix this problem, it was caused by some leader in your game that does not have a name and there was a mistake in handling this edge case. Let me know if the error is still there (or any other problem of course)

**Comment by MethodOfMadness** [comment]
Hi, thanks for the fix, I've been saving the autosaves and tried parse_saves.exe on them from the 4.2 release which looked like it worked without issues.  The Dashboard also seems to be working fine with the updated database **however**, it did spit out a LOT of warnings. [See this copy of the console output](https://github.com/eliasdoehne/stellaris-dashboard/files/9204104/dashboard_4.2.console.output.txt)

If that is all working as intended, then I think everything is good. :)

**Comment by eliasdoehne** [comment]
@MethodOfMadness is that output from the same save game? Are you by any chance playing an old version of stellaris (before the overlord DLC release)?

**Comment by MethodOfMadness** [comment]
Sorry, I didn't see this message.  The steps to get that output were:
1. download the new version of the dashboard
2. copy the output\db folder from the old version to the new version
3. rename Stellaris save file folder
4. copy all existing save files for the current game back into the proper Stellaris savefile location (I've been using a cmd script to back up the savefiles during the games while dashboard wasn't working)
5. run parse_saves to get the data into the databank
6. run dasboard.exe to view the data
I'm playing 3.4.4, so not the absolute newest, but definitely after Overlord, although I do not have the Overlord DLC.
However, there is data from much older games in the databank... not sure if that matters.

Also, I just re-started dashboard.exe (to check what was in the database) and it didn't give me all of those warnings this time. It still gave me the warnings that have an actual empire name at the end of the line (are those only the empires I was playing when making the saves?) but it no longer has the warnings with "received None" at the end of the line, so maybe that was just the first time dashboard was run after running parse_saves?  I don't have a newer savefile since then, so not sure if it happens after adding any additional data.  I should have some more saves this evening, so I'll let you know what happens.

**Comment by MethodOfMadness** [comment]
We've played further, so I had some more autosaves and the dashboard processed them all without giving a lot of warnings (just the usual amount).
