### ISSUE TITLE
Empire names are not showing

### ISSUE THREAD

**Issue by Dmitrykrz** [eliasdoehne/stellaris-dashboard#72]
I see strange placeholders instead of real names
![image](https://user-images.githubusercontent.com/25010053/187441588-b97ae495-b474-4326-9902-9b786733e71b.png)

**Comment by eliasdoehne** [comment]
Hi @Dmitrykrz , are you using any mods that might introduce different name lists? You may need to configure the dashboard program so it looks for the right localization files, I wrote a comment explaining a bit more here: https://github.com/eliasdoehne/stellaris-dashboard/issues/69#issuecomment-1193350018

Let me know if that helps or if there is still a problem

**Comment by Dmitrykrz** [comment]
> 

Only gigastructural engineering

**Comment by Dmitrykrz** [comment]
> Hi @Dmitrykrz , are you using any mods that might introduce different name lists? You may need to configure the dashboard program so it looks for the right localization files, I wrote a comment explaining a bit more here: [#69 (comment)](https://github.com/eliasdoehne/stellaris-dashboard/issues/69#issuecomment-1193350018)
> 
> Basically the likely solution is to look for the game and mod files where the names are defined, copy them to some common folder, and then point the dashboard to that folder for the localization files.
> 
> Let me know if that helps or if there is still a problem

Thanks, it works after copying yml files

**Comment by eliasdoehne** [comment]
Great, thanks for confirming the fix!
