### ISSUE TITLE
dashboard.exe keeps crashing, unable to correctly identify the game and savefile

### ISSUE THREAD

**Issue by Abolohit** [eliasdoehne/stellaris-dashboard#77]
Same as description of the issue. I am using some mods like Real Space, Real Galaxy, Real Sol Textures and some other mods in my gameplay. I created a new save with Real Sol Expansion Sol system as the home system. The dashboard, when opened via in game browser, keeps saying unidentified game and when the new autosave occurs, crashes. Thus, the dashboard is unable to fullfill its duty, which is, to keep a timeline record of the events of my gameplay

**Comment by chennin** [comment]
Please upload the save game that causes a crash here

**Comment by Abolohit** [comment]
[ironman.zip](https://github.com/eliasdoehne/stellaris-dashboard/files/10080361/ironman.zip)
Here you go

**Comment by chennin** [comment]
This is the crash:
```
Traceback (most recent call last):
  File "/tmp/stellaris-dashboard/stellarisdashboard/parsing/timeline.py", line 59, in process_gamestate
    self._process_gamestate(db_game)
  File "/tmp/stellaris-dashboard/stellarisdashboard/parsing/timeline.py", line 109, in _process_gamestate
    data_processor.extract_data_from_gamestate(
  File "/tmp/stellaris-dashboard/stellarisdashboard/parsing/timeline.py", line 851, in extract_data_from_gamestate
    self._extract_country_economy(country_data, country_data_dict)
  File "/tmp/stellaris-dashboard/stellarisdashboard/parsing/timeline.py", line 929, in _extract_country_economy
    country_data.net_influence += influence
TypeError: unsupported operand type(s) for +=: 'float' and 'list'
```
I will take a look soon :tm:

**Comment by chennin** [comment]
This savefile has two identical influence values in every country_power_projection.  I'm going to guess this is a mod messing things up.

```
                                        country_power_projection={
                                                influence=0.24488
                                                influence=0.24488
                                        }
```
But, the dashboard can probably work around it. @Abolohit can you please confirm how much influence you are getting from power projection in this save? It is probably 0.24; I I just want to check it's not 0.48 or something

On the influence tooltip here:
![image](https://user-images.githubusercontent.com/2653277/203874572-490d123a-ecc6-4339-8261-7e951386eaa6.png)

**Comment by Abolohit** [comment]
Yes, it is 0.24 from power projection.

**Comment by chennin** [comment]
To be fair, I didn't look at the mods listed (and I don't plan to due to their download size), so I can't say for sure if a mod is at fault, but none of my saves repeat keys like this one. In any case, the PR I just opened will prevent the crash, and use the first value (if they are repeated) when calculating the country economy. Thanks for the report!

In case you're not familiar the code flow: The next step is that eliasdoehne reviews my PR, and merges it (or has feedback that we work on). Then, depending on how you installed the dashboard, you will likely need to wait for a new release to be made.

**Comment by Abolohit** [comment]
Ok, thanks for looking into the matter, and getting a solution ready👍

So, the new pull request will be checking whether any economy parameter values are being repeated, and then use only the first one if it finds a repetition?

**Comment by eliasdoehne** [comment]
Thanks for the discussion and the quick fix! I will merge the pending PRs today and prepare a new github release and steam workshop update tomorrow.
