### ISSUE TITLE
version of Plotly installed by default does not work with graph

### ISSUE THREAD

**Issue by sinker1345** [eliasdoehne/stellaris-dashboard#9]
tested on Linux and windows, plotly v 3.1.1 is installed by default however when trying to view the timeline you receive an error in the terminal/command window

hovermode' property is an enumeration that may be specified as: - One of the following enumeration values: ['x', 'y', 'closest', False]

manually uninstalling plotly and installing v 2.0.0 via pip resolves this issue. did not test versions between 2.0.0 and 3.1.1

**Comment by sinker1345** [comment]
Awesome, thank you. I wish I could code so I could have been more help!

**Comment by eliasdoehne** [comment]
These issues should be fixed are in the (pre-)release version [v0.1.5-alpha](https://github.com/eliasdoehne/stellaris-dashboard/releases/tag/v0.1.5-alpha). I am closing the issue for now, if the problems still occur, please let me know.
