### ISSUE TITLE
Encoding problem displaying some names

### ISSUE THREAD

**Issue by chennin** [eliasdoehne/stellaris-dashboard#92]
Something is wrong with the encoding here:

![image](https://user-images.githubusercontent.com/2653277/208546194-1d725664-68b5-4015-b00e-d95973c1353b.png)

**The working one parses the save file as utf-8 (I added the warning on line 391 of `stellarisdashboard/parsing/save_parser.py`)**. This file is actually from 2022 Oct 25.

[2217.09.17.sav.zip](https://github.com/eliasdoehne/stellaris-dashboard/files/10263450/2217.09.17.sav.zip)

```
ForkPoolWorker-2 - 2022-12-19 18:12:30,281 - stellarisdashboard.parsing.save_parser - INFO - Parsing Save File /home/.../stellaris-dashboard/saves/ellircommonwealth_1004844130/2217.09.17.sav...
ForkPoolWorker-2 - 2022-12-19 18:12:30,422 - stellarisdashboard.parsing.save_parser - WARNING - Caught UnicodeError, trying utf-8 next. 'charmap' codec can't decode byte 0x8d in position 10951350: character maps to <undefined>
MainProcess - 2022-12-19 18:12:40,611 - stellarisdashboard.parsing.save_parser - INFO - Parsed save file /home/.../stellaris-dashboard/saves/ellircommonwealth_1004844130/2217.09.17.sav in 10.330240488052368 seconds.
```
Here is how it looks in the DB:
```
$ echo "select country_name from countrytable where country_id_in_game = 0;" | sqlite3 output/db/ellircommonwealth_1004844130.db
{"key": "format.olig_tech.3", "variables": [{"key": "oligarchic_tech", "value": {"key": "Commonwealth"}}, {"key": "This.GetSpeciesName", "value": {"key": "Ellir\u00ed"}}]}
```

Using [FTFY](https://ftfy.readthedocs.io/en/latest/) to explain this key yields nothing to change:

```
>>> from ftfy import fix_and_explain, apply_plan
>>> s = "Ellir\u00ed"
>>> fixed, explanation = fix_and_explain(s)
>>> fixed
'Ellirí'
>>> explanation
[]
```

**The non-working one parses as cp1252 (no warning thrown).** This file is from 2022 Dec 02.

[2242.02.17.sav.zip](https://github.com/eliasdoehne/stellaris-dashboard/files/10263452/2242.02.17.sav.zip)

```
ForkPoolWorker-1 - 2022-12-19 18:06:04,319 - stellarisdashboard.parsing.save_parser - INFO - Parsing Save File /home/.../stellaris-dashboard/saves/mpellircommonwealth_-1348400465/2242.02.17.sav...
MainProcess - 2022-12-19 18:06:10,322 - stellarisdashboard.parsing.save_parser - INFO - Parsed save file /home/.../stellaris-dashboard/saves/mpellircommonwealth_-1348400465/2242.02.17.sav in 6.004239320755005 seconds.
```
Here is how it looks in the DB:
```
$ echo "select country_name from countrytable where country_id_in_game = 0;" | sqlite3 output/db/mpellircommonwealth_-1348400465.db
{"key": "format.olig_tech.3", "variables": [{"key": "oligarchic_tech", "value": {"key": "Commonwealth"}}, {"key": "This.GetSpeciesName", "value": {"key": "Ellir\u00c3\u00ad"}}]}
```

Using FTFY corrects something:

```
>>> from ftfy import fix_and_explain, apply_plan
>>> s = "Ellir\u00c3\u00ad"
>>> fixed, explanation = fix_and_explain(s)
>>> fixed
'Ellirí'
>>> explanation
[('encode', 'latin-1'), ('decode', 'utf-8')]
```

Not sure the best way to proceed here. Is it time to assume a save encoding of utf-8?

**Comment by chennin** [comment]
As a more ridiculous example from a different save, this is supposed to be `Ûrîan Civilization`:

![image](https://user-images.githubusercontent.com/2653277/208548710-fd233418-9577-4dc9-b696-c896205aafcd.png)

**Comment by chennin** [comment]
It belatedly occurred to me that the saves have a bunch of mods.  So here's an unmodded 3.6.1 save.

![image](https://user-images.githubusercontent.com/2653277/208683823-ecc9cafd-f6a5-4f13-9629-3c903ba5f05a.png)

[2200.01.01.sav.zip](https://github.com/eliasdoehne/stellaris-dashboard/files/10269005/2200.01.01.sav.zip)

**Comment by MichaelMakesGames** [comment]
The provided save seems to work fine for me. I think this might've been fixed with other work on localization. @chennin is it fine to close this?

**Comment by chennin** [comment]
Hmm.. seems fine on new saves. I even booted my old Windows install to test.
![image](https://github.com/eliasdoehne/stellaris-dashboard/assets/2653277/8d6f4b0d-e8c5-4484-9621-91bf0fb9669e)
(The middle one is a quite old save from this bug report.. I am not too inclined to chase the loc errors on old saves.)
